export const PROTOCOL = 773;
export const HS_LOGIN = 2;

export const LOGIN = { DISCONNECT: 0x00, SUCCESS: 0x02, C2S_START: 0x00, C2S_ACK: 0x03 };

export const CFG = {
  DISCONNECT: 0x02,
  CUSTOM_PAYLOAD: 0x01,
  FINISH: 0x03,
  KEEP_ALIVE: 0x04,
  PING: 0x05,
  REGISTRY_DATA: 0x07,
  FEATURE_FLAGS: 0x0c,
  UPDATE_TAGS: 0x0d,
  SELECT_KNOWN_PACKS: 0x0e,
  C2S_SETTINGS: 0x00,
  C2S_CUSTOM_PAYLOAD: 0x02,
  C2S_FINISH: 0x03,
  C2S_KEEP_ALIVE: 0x04,
  C2S_PONG: 0x05,
  C2S_SELECT_KNOWN_PACKS: 0x07,
};

/** ClientboundGameEventPacket.Type.LEVEL_CHUNKS_LOAD_START (PlayerList.sendLevelInfo). */
export const GAME_EVENT_LEVEL_CHUNKS_LOAD_START = 13;

export const PLAY = {
  LOGIN: 0x30,
  CHUNK_BATCH_FINISHED: 0x0b,
  LIGHT_UPDATE: 0x2f,
  GAME_EVENT: 0x26,
  MAP_CHUNK: 0x2c,
  UPDATE_VIEW_POSITION: 0x5c,
  UPDATE_TIME: 0x6f,
  SET_TICKING_STATE: 0x7d,
  STEP_TICK: 0x7e,
  KEEP_ALIVE: 0x2b,
  POSITION: 0x46,
  PING: 0x3b,
  ENTITY_VELOCITY: 0x63,
  C2S_TELEPORT_CONFIRM: 0x00,
  C2S_CHUNK_BATCH_RECEIVED: 0x0a,
  C2S_TICK_END: 0x0c,
  C2S_KEEP_ALIVE: 0x1b,
  C2S_PLAYER_LOADED: 0x2b,
  C2S_PONG: 0x2c,
  C2S_CUSTOM_PAYLOAD: 0x15,
  C2S_POSITION: 0x1d,
  C2S_MOVE_ROT: 0x1f,
  C2S_POSITION_LOOK: 0x1e,
  C2S_MOVE_STATUS: 0x20,
};

/** Vanilla client tick period (20 TPS). */
export const CLIENT_TICK_MS = 50;

export const LOG_LEVELS = { error: 0, warn: 1, info: 2, debug: 3 };

export const DECODE_MAX = Number(process.env.MC_CLIENT_DECODE_MAX) || 160;
