#ifndef MC_PACKET_IDS_H
#define MC_PACKET_IDS_H

/** Minecraft Java 1.21.10 (protocol 773). */
#define MC_PROTOCOL_VERSION 773

/* handshaking */
#define MC_PKT_HS_SET_PROTOCOL 0x00

/* login */
#define MC_PKT_LOGIN_DISCONNECT 0x00
#define MC_PKT_LOGIN_ENCRYPTION_BEGIN 0x01
#define MC_PKT_LOGIN_SUCCESS 0x02
#define MC_PKT_LOGIN_COMPRESS 0x03
#define MC_PKT_C2S_LOGIN_START 0x00
#define MC_PKT_C2S_LOGIN_ACKNOWLEDGED 0x03

/* configuration + common */
#define MC_PKT_COMMON_CUSTOM_PAYLOAD 0x01
#define MC_PKT_COMMON_UPDATE_TAGS 0x0d
#define MC_PKT_CFG_REGISTRY_DATA 0x07
#define MC_PKT_CFG_FEATURE_FLAGS 0x0c
#define MC_PKT_CFG_SELECT_KNOWN_PACKS 0x0e
#define MC_PKT_CFG_FINISH 0x03
#define MC_PKT_CFG_KEEP_ALIVE 0x04
#define MC_PKT_CFG_PING 0x05
#define MC_PKT_CFG_RESET_CHAT 0x06
#define MC_PKT_C2S_CFG_SETTINGS 0x00
#define MC_PKT_C2S_CFG_CUSTOM_PAYLOAD 0x02
#define MC_PKT_C2S_CFG_FINISH 0x03
#define MC_PKT_C2S_CFG_KEEP_ALIVE 0x04
#define MC_PKT_C2S_CFG_PONG 0x05
#define MC_PKT_C2S_CFG_SELECT_KNOWN_PACKS 0x07

/* play S2C (GameProtocols.java CLIENTBOUND, 1.21.10 release / protocol 773) */
#define MC_PKT_PLAY_DIFFICULTY 0x0a
#define MC_PKT_PLAY_CHUNK_BATCH_FINISHED 0x0b
#define MC_PKT_PLAY_CHUNK_BATCH_START 0x0c
#define MC_PKT_PLAY_BLOCK_CHANGE 0x08
#define MC_PKT_PLAY_GAME_STATE_CHANGE 0x26
#define MC_PKT_PLAY_UNLOAD_CHUNK 0x25
#define MC_PKT_PLAY_INITIALIZE_WORLD_BORDER 0x2a
#define MC_PKT_PLAY_KEEP_ALIVE 0x2b
#define MC_PKT_PLAY_MAP_CHUNK 0x2c
#define MC_PKT_PLAY_LIGHT_UPDATE 0x2f
#define MC_PKT_PLAY_LOGIN 0x30
#define MC_PKT_PLAY_PING 0x3b
#define MC_PKT_PLAY_ABILITIES 0x3e
#define MC_PKT_PLAY_PLAYER_INFO 0x44
#define MC_PKT_PLAY_POSITION 0x46
#define MC_PKT_PLAY_UPDATE_VIEW_POSITION 0x5c
#define MC_PKT_PLAY_UPDATE_VIEW_DISTANCE 0x5d
#define MC_PKT_PLAY_SPAWN_POSITION 0x5f
#define MC_PKT_PLAY_EXPERIENCE 0x65
#define MC_PKT_PLAY_UPDATE_HEALTH 0x66
#define MC_PKT_PLAY_SIMULATION_DISTANCE 0x6d
#define MC_PKT_PLAY_UPDATE_TIME 0x6f
#define MC_PKT_PLAY_SET_TICKING_STATE 0x7d
#define MC_PKT_PLAY_STEP_TICK 0x7e

/* play C2S */
#define MC_PKT_C2S_TELEPORT_CONFIRM 0x00
#define MC_PKT_C2S_CHAT_COMMAND 0x06
#define MC_PKT_C2S_CHAT 0x08
#define MC_PKT_C2S_TICK_END 0x0c
#define MC_PKT_C2S_KEEP_ALIVE 0x1b
#define MC_PKT_C2S_PLAYER_LOADED 0x2b
#define MC_PKT_C2S_POSITION 0x1d
#define MC_PKT_C2S_POSITION_LOOK 0x1e
#define MC_PKT_C2S_MOVE_STATUS 0x20
#define MC_PKT_C2S_MOVE_ROT 0x1f
#define MC_PKT_C2S_CUSTOM_PAYLOAD 0x15
#define MC_PKT_C2S_PLAYER_ACTION 0x28
#define MC_PKT_C2S_PLAYER_INPUT 0x2a
#define MC_PKT_C2S_SWING 0x3c
#define MC_PKT_C2S_USE_ITEM_ON 0x3f
#define MC_PKT_C2S_USE_ITEM 0x40
#define MC_PKT_C2S_CHUNK_BATCH_RECEIVED 0x0a
#define MC_PKT_C2S_SET_CARRIED_ITEM 0x34
#define MC_PKT_C2S_PONG 0x2c

#define MC_STATE_HANDSHAKE 0
#define MC_STATE_LOGIN 1
#define MC_STATE_CONFIGURATION 2
#define MC_STATE_PLAY 3

/* status */
#define MC_PKT_STATUS_RESPONSE 0x00
#define MC_PKT_STATUS_PONG 0x01
#define MC_PKT_C2S_STATUS_REQUEST 0x00
#define MC_PKT_C2S_STATUS_PING 0x01

/* handshaking set_protocol nextState */
#define MC_HS_STATUS 1
#define MC_HS_LOGIN 2
#define MC_HS_TRANSFER 3

#endif
